Bài 1: Một 3D Tree đang được dựng từ tập điểm 3 chiều, sử dụng trung vị chiều để chia thành 2 nhánh cây cho tới khi mọi node lá chứa từ 2 điểm dữ liệu trở xuống. Vẽ cây sau khi được dựng hoàn thành

In [145]:
import numpy as np

x = np.array([-1.58, 0.91, -0.73, -4.22, 4.19, -0.33])
y = np.array([-2.01, 3.98, 4.00, 1.16, -2.02, 2.15])
z = np.array([-4, -2.8, 1.3, 0.16, -1.05, 2])
point = np.vstack((x, y)).T

point

array([[-1.58, -2.01, -4.  ],
       [ 0.91,  3.98, -2.8 ],
       [-0.73,  4.  ,  1.3 ],
       [-4.22,  1.16,  0.16],
       [ 4.19, -2.02, -1.05],
       [-0.33,  2.15,  2.  ]])

In [146]:
def get_mid_range(data, column=0):
    """ Hàm lấy trung vị chiều
    chiều x column=0
    chiều y column=1
    chiều z column=2
    """
    midrange = (data[:, column].max() + data[:, column].min())/2
    return midrange      

def split_by(point, value, column=0):
    """ Chia cây theo chiều 
    chiều x column=0
    chiều y column=1
    chiều z column=2
    """
    split1 = point[point[:, column] <= value]
    split2 = point[point[:, column] > value]
    return split1, split2

In [147]:
x_midrange = get_mid_range(point)
y1, y2 = split_by(point, x_midrange)

# Split values of x1
y1

array([[-1.58, -2.01, -4.  ],
       [-0.73,  4.  ,  1.3 ],
       [-4.22,  1.16,  0.16],
       [-0.33,  2.15,  2.  ]])

In [148]:
# Split values of x1
y2

array([[ 0.91,  3.98, -2.8 ],
       [ 4.19, -2.02, -1.05]])

In [149]:
y1_midrange = get_mid_range(y1, column=1)

print (y1_midrange)

0.9950000000000001


In [150]:
z1,z2 = split_by(y1, y1_midrange, column=1)
z1

array([[-1.58, -2.01, -4.  ]])

In [151]:
z2

array([[-0.73,  4.  ,  1.3 ],
       [-4.22,  1.16,  0.16],
       [-0.33,  2.15,  2.  ]])

In [152]:
z2_midrange = get_mid_range(z2, column=2)

print (z2_midrange)

1.08


Bài 2 :Truyền vào tham số thích hợp để chia cây ra theo chiều thích hợp

In [153]:
x1,x2 = split_by()
x1

array([[-4.22,  1.16,  0.16]])

In [154]:
x2

array([[-0.73,  4.  ,  1.3 ],
       [-0.33,  2.15,  2.  ]])